#!/usr/bin/env bash
#                                           :                                         
#         ,;                               t#,                                       .
#       f#i                t              ;##W.     j.                              ;W
#     .E#t                 ED.           :#L:WE     EW,          GEEEEEEEL         f#E
#    i#W,     :KW,      L  E#K:         .KG  ,#D    E##j         ,;;L#K;;.       .E#f 
#   L#D.       ,#W:   ,KG  E##W;        EE    ;#f   E###D.          t#E         iWW;  
# :K#Wfff;      ;#W. jWi   E#E##t      f#.     t#i  E#jG#W;         t#E        L##Lffi
# i##WLLLLt      i#KED.    E#ti##f     :#G     GK   E#t t##f        t#E       tLLG##L 
#  .E#L           L#W.     E#t ;##D.    ;#L   LW.   E#t  :K#E:      t#E         ,W#i  
#    f#E:       .GKj#K.    E#ELLE##K:    t#f f#:    E#KDDDD###i     t#E        j#E.   
#     ,WW;     iWf  i#K.   E#L;;;;;;,     f#D#;     E#f,t#Wi,,,     t#E      .D#j     
#      .D#;   LK:    t#E   E#t             G#t      E#t  ;#W:       t#E     ,WK,      
#        tt   i       tDj  E#t              t       DWi   ,KK:       fE     EG.       
#                                                                     :     ,         

export EDITOR='nvim'                      # Neovim

export HISTSIZE='32768'                   # 32³ entries
export HISTFILESIZE=${HISTSIZE}           # Default is 500
export HISTCONTROL='ignoreboth'           # No dupes or space preceeding commands

export NODE_REPL_HISTORY=~/.node_history  # Enable persistent node REPL history
export NODE_REPL_HISTORY_SIZE=${HISTSIZE} # Default is 1000
export NODE_ENV='development'             # Use dev node env if undefined

export GPG_TTY=$(tty)                     # GPG signing key

export LANG='en_US.UTF-8'                 # Prefer US English and use UTF-8
export LC_ALL='en_US.UTF-8' 

export LESS_TERMCAP_mb=$(printf $RED)     # Start blink
export LESS_TERMCAP_md=$(printf $GREEN)   # Start bold
export LESS_TERMCAP_so=$(printf $YELLOW)  # Start standout
export LESS_TERMCAP_se=$(printf '\e[0m')  # Stop standout
export LESS_TERMCAP_me=$(printf '\e[0m')  # Turn off bold, blink, underline
export LESS_TERMCAP_us=$(printf $BLUE)    # Start underline
export LESS_TERMCAP_ue=$(printf '\e[0m')  # Stop underline

export MANPAGER='less -X'                 # Disable clearing man page on quit

if [ "$(uname)" = "Darwin" ]; then        # macOS only
  export ANDROID_HOME='/usr/local/opt/android-sdk';
  export JAVA_HOME=$(/usr/libexec/java_home)
  export PKG_CONFIG_PATH='/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig'
fi
