#!/usr/bin/env bash
#   __    ____    ______  ______  __  __     
#  /\ \_ /\  _`\ /\  _  \/\__  _\/\ \/\ \    
#  \/'__`\ \ \L\ \ \ \L\ \/_/\ \/\ \ \_\ \   
#  /\ \_\_\ \ ,__/\ \  __ \ \ \ \ \ \  _  \  
#  \ \____ \ \ \/  \ \ \/\ \ \ \ \ \ \ \ \ \ 
#   \/\ \_\ \ \_\   \ \_\ \_\ \ \_\ \ \_\ \_\
#    \ `\_ _/\/_/    \/_/\/_/  \/_/  \/_/\/_/
#     `\_/\_\                                
#        \/_/                                

if [ "$(uname)" = "Darwin" ]; then
  # Added first to prevent overwriting issues
  export PATH="$HOME/.rvm/gems/ruby-2.4.0/bin"
fi

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

if [ "$(uname)" = "Linux" ]; then
  NVM_DIR="/usr/local/share/.nvm";
else
  NVM_DIR="$HOME/.nvm"
fi

export CDPATH='.:~/:..:../..'

export NVM_DIR;
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh";
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

if [ "$(uname)" = "Darwin" ]; then
  export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
  export PATH="$HOME/Library/Python/3.6:$PATH"
  export PATH="$HOME/Library/Haskell/bin:$PATH"
  export PATH="$HOME/.cabal/bin:$PATH"
  export PATH="$HOME/src/mongodb/bin:$PATH"
  export PATH="$HOME/.fastlane/bin:$PATH"
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  export PATH="/usr/local/opt/qt5/bin:$PATH"
  export PATH="$HOME/src/miniconda3/bin:$PATH"

  export PATH="${PATH}:/usr/local/opt/android-sdk/tools"
  export PATH="${PATH}:/usr/local/opt/android-sdk/platform-tools"

  # Added last To prevent bootstrapping issues
  export PATH="$PATH:$HOME/.rvm/bin"
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
fi
